title: Tracer un graphique à barres
hero_image: images/banner.png
description: Trace un graphique à barres
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Introduction
